# PIPELINE DEFINITION
# Name: ml-pipeline
# Description: Pipeline for image classification
# Inputs:
#    url: str
components:
  comp-download-data:
    executorLabel: exec-download-data
    inputDefinitions:
      parameters:
        url:
          parameterType: STRING
    outputDefinitions:
      artifacts:
        output_csv:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
deploymentSpec:
  executors:
    exec-download-data:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - download_data
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet     --no-warn-script-location 'pandas'\
          \ 'openpyxl' 'kfp==2.0.1' && \"$0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)

          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          python3 -m kfp.components.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef download_data(url:str, output_csv:Output[Dataset]):\n    import\
          \ pandas as pd\n\n    # Use pandas excel reader\n    df = pd.read_excel(url)\n\
          \    df = df.sample(frac=1).reset_index(drop=True)\n    df.to_csv(output_csv.path,\
          \ index=False)\n\n"
        image: python:3.7
pipelineInfo:
  description: Pipeline for image classification
  name: ml-pipeline
root:
  dag:
    tasks:
      download-data:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-download-data
        inputs:
          parameters:
            url:
              componentInputParameter: url
        taskInfo:
          name: download-data
  inputDefinitions:
    parameters:
      url:
        parameterType: STRING
schemaVersion: 2.1.0
sdkVersion: kfp-2.0.1
